version: '3'
services:
  app:
    # restart: on-failure
    build: .
    # depends_on:
    #   - postgres
    environment:
      DATABASE_URL: postgres://dbdis:1234@postgres:5432/disastor
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
      - '5000:5000'
      - '5500:5500'
    command: npm run pm2-eco-dev
    # command: npm run run-prisma
    volumes:
      - .:/app
      # - /app/node_modules

  postgres:
    image: postgres:12.16-bullseye
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dbdis
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: disastor
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
